services:
  frontend:
    image: 192.168.56.43:80/container-training/frontend:0.1.0
    ports:
      - 8080:80
  greetings:
    image: 192.168.56.43:80/container-training/greetings:0.1.0
    environment:
      CORS_ORIGIN: 192.168.56.42:8080
      VISITS_BACKEND: http://visits:8080
      OLD_STAGER_ENABLED: 1
    ports:
      - 9292:9292
  visits:
    image: 192.168.56.43:80/container-training/visits:0.1.0
    volumes:
      - visits-data:/data
    environment:
      DATABASE_URL: file:/data/prod.db

volumes:
  visits-data: {}

