# frozen_string_literal: true

source 'https://rubygems.org'

ruby '3.3.7'

gem 'faraday', '~> 2.9'

gem 'liquid', '~> 5.5'

gem 'rack-cors', '~> 2.0'
gem 'rackup', '~> 2.1'
gem 'roda', '~> 3.81'

group :development do
  gem 'debug', '~> 1.9'
end
